services:
    app:
        build: .
        stdin_open: true
        tty: true
        env_file: .env
        environment:
          USE_TRAY: false
        volumes:
          - data:/app/session/

volumes:
  data: